# NUMPY Functions

In [1]:
import numpy as np

# arange() Function

In [2]:
#  np.arange(start, End , Steps)
arr1 = np.arange(1,13)
print (arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# linspace() Function

In [3]:
#The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number. 
#numpy.linspace(start,stop,num)
arr2 = np.linspace(2,5,7)
print (arr2)

[2.  2.5 3.  3.5 4.  4.5 5. ]


# reshape() Function

In [4]:
#The numpy.reshape() function shapes an array without changing the data of the array.
#Syntax:  numpy.reshape(array, shape, order = 'C')

#array reshaped with 2 rows and 6 columns :
arr3 = arr1.reshape(2,6)
print(arr3)

# Constructs 3D array
arr4 = arr1.reshape(2,3,2)
print(arr4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
arr5 = np.arange(1,13).reshape(3,4)
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# ravel() Function 

In [6]:
#The numpy.ravel() functions returns contiguous flattened array(1D array with all the input-array elements and with the same type as it). A copy is made only if needed. 
#Syntax :  numpy.ravel(array, order = 'C')

arr5.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose() Function

In [8]:
#The numpy.transpose() function changes the row elements into column elements and the column elements into row elements. The output of this function is a modified array of the original one.
#Syntax : numpy.transpose(arr, axis=None) 
#OR Syntax : numpy.T

arr5.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])