In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print (arr)

[1 2 3 4]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim

1

In [5]:
arr2 = np.array([[1,2,3,4] , [5,6,7,8]])

In [6]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
type(arr2)

numpy.ndarray

In [8]:
arr2.ndim

2

In [9]:
arr.size

4

In [10]:
arr2.size

8

In [11]:
arr.size

4

In [12]:
arr.shape

(4,)

In [13]:
arr2.shape

(2, 4)