# Mathematics Operation Using Numpy

In [1]:
import numpy as np

In [2]:
#Create Two matrix of 3x3 size.

arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print (arr1)
print (arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# + ,- , * ,& / operations 

In [3]:
#Using '+' operator 
a = arr1 + arr2
print (a)

#Using '-' operator 
b = arr1 - arr2
print(b)

#Using '*' operator 
c = arr1 * arr2
print(c)

#Using '/' operator 
d = arr1 / arr2
print(d)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
#using add() function
a = np.add(arr1 , arr2)
print(a)

#using subtract() function
b = np.subtract (arr1 , arr2)
print(b)

#using multiply() function
c = np.multiply (arr1 , arr2)
print(c)

#using divide() function
d = np.divide (arr1 , arr2)
print(d)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#Matrix Multiplication
#Using '@'
a = arr1 @ arr2
print (a)

#Using 'dot'
b = arr1.dot(arr2)
print (b)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# Maximun and Minimum in an array

In [6]:
#Maximum
#using max() function
a = arr1.max()
print (a)

#Index of Max value
b = arr1.argmax()
print (b)

#Max value in columns (0=column) 
c = arr1.max(axis = 0)
print (c)

#Max value in row (1 = row)
d = arr1.max(axis = 1)
print (d)

9
8
[7 8 9]
[3 6 9]


In [7]:
#Minimum
#using min() function
a = arr1.min()
print (a)

#Index of Max value
b = arr1.argmin()
print (b)

#Max value in columns (0=column) 
c = arr1.min(axis = 0)
print (c)

#Max value in row (1 = row)
d = arr1.min(axis = 1)
print (d)

1
0
[1 2 3]
[1 4 7]


# sum() Function

In [8]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#sum of all elements of matrix
arr1.sum()

#OR
np.sum(arr1)

45

In [10]:
#sum of all column elements of matrix
np.sum(arr1, axis=0)

array([12, 15, 18])

In [11]:
#sum of all row elements of matrix
np.sum(arr1, axis=1)

array([ 6, 15, 24])

In [12]:
#Average of Matrix
np.mean(arr1)

5.0

In [13]:
#Sq. root of Matrix
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [14]:
#Standered deviation of Matrix
np.std(arr1)

2.581988897471611

In [15]:
#Exponion of Matrix
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [16]:
#Lograthim of Matrix
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [17]:
#Lograthim of Matrix
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])