In [1]:
import numpy as np

In [2]:
matrix1 = np.array([[1,1,1] , [1,1,1] , [1,1,1]])
print(matrix1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
m1=np.ones(5)
print(m1)

[1. 1. 1. 1. 1.]


In [4]:
m1.dtype

dtype('float64')

In [5]:
m2 = np.ones((5,5) , dtype=int)
print(m2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
m3 = np.zeros((4,4) , dtype= int)
print(m3)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
m3 = np.zeros((4,4) , dtype= float)
print(m3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
m3 = np.zeros((4,4) , dtype= bool)
print(m3)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [9]:
m2 = np.ones((5,5) , dtype=bool)
print(m2)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [10]:
m2 = np.ones((5,5) , dtype=str)
print(m2)

[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]


In [15]:
m4 = np.empty((5,5) , dtype=int)
print(m4)

[[2026372248        539         64          0          0]
 [         0          0          0          0         57]
 [ 962868326  892547939  909521463 1701197106 1630941497]
 [ 909730869 1697658675 1633968944  825374309 1667512677]
 [ 926234167  842477617  943219044  959930930 1650799203]]
